### ISSUE TITLE
Leechblock on Chromebook

### ISSUE THREAD

**Issue by fmcgee311** [proginosko/LeechBlockNG-chrome#11]
Is there a way to block Task Manager on a Chromebook or keep Leechblock from appearing in Task Manager on a Chromebook?

**Comment by proginosko** [comment]
The following may provide a solution:

https://support.google.com/chrome/a/answer/2657289?hl=en (scroll down to **Task Manager** under **Apps and Extensions**)

https://www.chromium.org/administrators/policy-list-3#TaskManagerEndProcessEnabled

**Comment by fmcgee311** [comment]
Thank you, James!
Frank McGee
