### ISSUE TITLE
If new time period starts and currently viewed page is LeechBlock blocked page, then each next page will be blocked too even with enough time left.

### ISSUE THREAD

**Issue by Scharnvirk** [proginosko/LeechBlockNG-chrome#13]
As in title.

To reproduce the bug:
- set up a time limit per hour 
- exceed the time limit
- wait for new time period to start
- while being on the "The page you're trying to access has been blocked by LeechBlock." page, go to a page which is on the blocking list
- the page will be blocked immediately and timer will stay at 00:00.

Expected behavior:
- new page opens normally and timer starts at full allowed value

**Comment by sharmav39** [comment]
Did you ever find a solution to this?

I am encountering the same problem.

**Comment by derekgurney** [comment]
I'm also having this problem.

**Comment by proginosko** [comment]
I think this is related to #14. If so, it should be fixed in version 1.0.3.1 (currently pending review). Let me know.

**Comment by proginosko** [comment]
This should be resolved in version 1.0.6.2. Reopen this issue if you discover otherwise.
