### ISSUE TITLE
Show Timer On/Off per-group!

### ISSUE THREAD

**Issue by TheDemystifier** [proginosko/LeechBlockNG-chrome#2]
I have a group set to block all websites (*) past 2AM, But the thing is, it shows a timer at every website counting down time left till 2AM. And I don't want to hide the timer overall because it's useful otherwise, just not in this case!

It'd be great if you could provide an 'override' option in each group to hide the timer OR make the timer per-group (checked by default) instead of global!

Thanks!

**Comment by proginosko** [comment]
Implemented in v0.9.3.
