### ISSUE TITLE
LeechBlock blocks either everything or nothing at all

### ISSUE THREAD

**Issue by lunareagle403** [proginosko/LeechBlockNG-chrome#21]
I've used Leechblock for months now, and it's worked great. I have a set of keywords that I use it to block, and whenever it's overly sensitive to a website that it doesn't need to block, I add an exception for it. It has given me no problems - until today when it randomly decided to block EVERYTHING - except for the things I had already established exceptions to - while I was working. I haven't messed with it in weeks, if not months, and there was no reason for it to do this. I went and looked at the settings, and nothing looked wrong or out of place. I tried to edit the block set, and all that gave me was keeping ANYTHING from being blocked. This program has been really useful to me for blocking things that I don't want active, but it went haywire today. I'd really like it to actually work again.

**Comment by proginosko** [comment]
Which OS are you using?

Please export your settings to a text file (Options > General > Export Options to File) and email it to me (leechblockng@proginosko.com) so I can take a look and figure out what's up.

**Comment by proginosko** [comment]
I tracked down the bug, which was introduced in version 1.0.7.1. Sorry for the inconvenience! Should be fixed in version 1.0.7.2 (pending review in Chrome Web Store).
