### ISSUE TITLE
Override does not work

### ISSUE THREAD

**Issue by trymeouteh** [proginosko/LeechBlockNG-chrome#22]
When I use the override and enter in the password, it should allow me to access the blocked site for 5 minutes or however long I set it for. But this does not work and will continue to block the site as long the block set is active during that time,

I am using Brave 1.16.68

**Comment by proginosko** [comment]
Have you selected "Allow temporary override" for the relevant block set?

**Comment by trymeouteh** [comment]
> Have you selected "Allow temporary override" for the relevant block set?

Nope that that is why, thank you for the quick response.
