### ISSUE TITLE
No response from extension page when in incognito mode

### ISSUE THREAD

**Issue by Nice44449** [proginosko/LeechBlockNG-chrome#23]
When I use LeechBlock in Chrome's incognito mode, by looking at the network tab of Chrome's dev tools, after the page's url gets set to the delayed extension page url, I get no response to the request for the delayed page. The result is that the page is blocked, but I only want it to be delayed. (If I manually change the url to end in blocked instead of delayed, I still get no response. Both pages seem to work correctly in non-incognito mode though.)

**Comment by proginosko** [comment]
Please provide a series of steps to help me reproduce the issue. (Also, let me know which OS you are using.) Thanks!

**Comment by Nice44449** [comment]
I am using Windows 10.

Here is a series of steps to reproduce the issue:

1. Open an incognito window and a non-incognito window
2. In the non-incognito window, create a block set in "Options" for LeechBlock, and set it to use the (default) Delaying Page
3. (In the non-incognito window) go to Chrome://extensions and activate "Allow in Incognito" for LeechBlock
4. In the incognito window, go to a blocked page. I now see "Requests to the server have been blocked by an extension."

**Comment by proginosko** [comment]
Sorry for the delay in getting back to this. Thanks for providing these steps. I was able to reproduce the problem and it turned out to be a simple fix (a setting in the manifest file). It should work properly in incognito mode from version 1.0.11.1.
