### ISSUE TITLE
keywords in non-English language 

### ISSUE THREAD

**Issue by force1711** [proginosko/LeechBlockNG-chrome#24]
hi, 

the LB is very perfect and good. but the issue of blocking keywords in non English is very important. maybe its possbile to fix this?

many thanks.

**Comment by Lao-lao** [comment]
Same isuue. Please fix soon

**Comment by proginosko** [comment]
See discussion on Firefox version here:

https://github.com/proginosko/LeechBlockNG/issues/180

The fix for this issue is currently being tested for Firefox. Chrome fix will follow after that.
