### ISSUE TITLE
Issues with the extension on chrome

### ISSUE THREAD

**Issue by Tramirez** [proginosko/LeechBlockNG-chrome#25]
I am having issues with my kids school issues chrome book and the leech bloc app and the issue is when they sign out of the users account on district issued Chromebook the leech block extension resets and none of the data is saved on the computer making the password and everything get erased. Is there any way to fix that issue?

**Comment by proginosko** [comment]
I'm not quite sure why that would be happening, but one workaround would be to export the options to a text file (see Options > General > Export) and import them again whenever you need to.

**Comment by Tramirez** [comment]
These are the screen shots if how you can log out and back on and
leechblock history gets removed even after exporting

**Comment by proginosko** [comment]
There are no screenshots here, presumably because you attached them to an email. If you want to post them here, you'll need to use the GitHub website.

**Comment by Tramirez** [comment]
Ok. I'm familiar with github I've got an account. I've done some programing
if I find a code can you try to add it? What language did you code
leechblock with?

**Comment by proginosko** [comment]
What I mean is that you need to go to this issue on the GitHub website (link will be at the bottom of the email) and post a comment in this thread with the screenshots as an attachment.

**Comment by Tramirez** [comment]
![Screenshot 2020-12-20 at 7 02 00 PM](https://user-images.githubusercontent.com/12164011/102735365-144edc80-42f7-11eb-9b68-6f5464606a90.png)

**Comment by Tramirez** [comment]
So to the bottom right if students click sign out and then get to the mail google chrome page and sign out of the google and then sign back into the student account leeckblock gets fully erased

![Screenshot 2020-12-20 at 7 21 51 PM](https://user-images.githubusercontent.com/12164011/102736036-cdfa7d00-42f8-11eb-9321-dbdfad1d8f56.png)

**Comment by Tramirez** [comment]
![Screenshot 2020-12-20 at 7 21 40 PM](https://user-images.githubusercontent.com/12164011/102736055-d9e63f00-42f8-11eb-93c0-0ef57af81e23.png)

**Comment by Tramirez** [comment]
ok so with this I am trying to show you what students do and even after exporting the file it will erase everything when they sign out of the google account.

**Comment by proginosko** [comment]
I don't know why that is happening. Simply exporting the file will not prevent the settings being erased. It only provides you with a backup of the settings, which you'll need to import again after the settings are erased.

The problem might have to do with Google sync. Do you have the LeechBlock option "Use sync storage for options" selected? If so, try unselecting it and see if that resolves the issue. Alternatively, if it is not selected, try selecting it and then following these steps:

1. Log in to a student account.
2. Set up the LeechBlock options (you can import your previously exported file).
3. Check that "Use sync storage for options" is selected.
3. Click the button "Export Options to Sync Storage" (just to make sure the options are pushed to sync storage).
3. Log out of the account.
4. Log back in to the account and see if the LeechBlock options have been preserved.

You might also need to experiment with your Google sync settings. Go to chrome://settings/syncSetup/advanced in your browser. By default, Chrome syncs everything, but you can customize your settings to activate/deactivate syncing of extensions.
