### ISSUE TITLE
Any possibility to prevent oneself from uninstalling Leechblock on Chrome?

### ISSUE THREAD

**Issue by emmaparker96** [proginosko/LeechBlockNG-chrome#26]
It is very easy to uninstall Leechblock from Chrome. You simply need to right-click on the icon and click uninstall. I find myself doing this on days when I don't have much willpower.
Is there any way to prevent this?

**Comment by proginosko** [comment]
See FAQ entry here:

https://www.proginosko.com/leechblock/faq/remove-extension-chrome/

Let me know if you have any questions.

**Comment by AnonymousWatch3r** [comment]
Hi, I'm having trouble doing this on linux. Can anyone help me out a little on what to do. Love the extension, just fall into the habit of disabling it whenever I want to continue watching youtube, for example. I use leechblock on brave.

>
