### ISSUE TITLE
Show Timer as Icon Badge

### ISSUE THREAD

**Issue by jiggey** [proginosko/LeechBlockNG-chrome#3]
Competitors like StayFocusd indicate the remaining time as a badge in the icon.
It would be great if this option also existed in LeechBlock
![requestleechblock](https://user-images.githubusercontent.com/18258350/35196893-8a1b5382-fed8-11e7-8079-cff9f598a239.png)

chrome.browserAction.setBadgeText({text: "21:45"});

**Comment by proginosko** [comment]
Great suggestions! I'll add that in the next version.

**Comment by proginosko** [comment]
Added in version 0.8.1. Badge text can't be more than 4 characters, so timer is only shown when time left is less than 10 minutes (9:59, etc.).
