### ISSUE TITLE
cannot export options to sync storage: QUOTA_BYTES_PER_ITEM quota exceeded

### ISSUE THREAD

**Issue by kamakshidasan** [proginosko/LeechBlockNG-chrome#31]
I have a really long list of urls that I block, so when I tried to sync to storage, I got the following message.

![error-message](https://user-images.githubusercontent.com/9362064/115965037-d5e75980-a544-11eb-8ad2-7add0f1fb941.PNG)

I checked the error messages, and I got the below message: "cannot export options to sync storage: QUOTA_BYTES_PER_ITEM quota exceeded"

![error-message2](https://user-images.githubusercontent.com/9362064/115965033-d4b62c80-a544-11eb-8d0f-e9f442aacd31.PNG)

So I google around and I found this link: https://stackoverflow.com/questions/33015723/unchecked-runtime-lasterror-while-running-storage-set-quota-bytes-per-item-quot

From the looks of it, I think all that has to be done is add "unlimitedStorage" to the manifest.json file.

**Comment by kamakshidasan** [comment]
Pull Request: https://github.com/proginosko/LeechBlockNG-chrome/pull/32

**Comment by proginosko** [comment]
Thanks for this report. Did you test this solution?

Roughly how long is your list of URLs? Can it be simplified with wildcards?

**Comment by kamakshidasan** [comment]
I have about 4300 URLs: and all distinct: https://pastebin.com/vYc3KVwc

**Comment by proginosko** [comment]
I see what you mean! At what point would it be more efficient to block everything and just use a whitelist? 😃
