### ISSUE TITLE
A way to block the domain of the site if there is no path but not block the domain if there is a path

### ISSUE THREAD

**Issue by shabbs15** [proginosko/LeechBlockNG-chrome#33]
This would be beneficial for example on reddit.

Sometimes I need some help with something and someone has made a reddit post about it. With this feature enabled, I can click and view the post and it works fine. However, I wouldn't be able to browse reddit since browsing doing so would be blocked seeing as it doesn't require a specific additional path to browse.

tldr: reddit.com is blocked but not reddit.com/r/learnprogramming/comments/66u0v7/what_is_the_best_tutorial_to_learn_both_gitgithub/

**Comment by proginosko** [comment]
Enter this in the list of sites:
`reddit.com`
`+reddit.com/r/`

**Comment by shabbs15** [comment]
you're a legend
