### ISSUE TITLE
LeechBlockNG doesn't seem to work in Vivaldi browser

### ISSUE THREAD

**Issue by tuket** [proginosko/LeechBlockNG-chrome#34]
Hello,
Vivaldi is a chrome-based browser, so I installed LeechBlockNG from the Chrome Web Store. But webpages are not getting blocked. Do you think there is any chance this extension could work in Vivaldi?
Thanks!

**Comment by proginosko** [comment]
It used to work with Vivaldi, so I'm not sure why it wouldn't work now.

Export your settings to a text file (Options > General > Export Options to File) and email them to me (leechblockng@proginosko.com) so I can check there isn't a problem with your settings.

**Comment by tuket** [comment]
The settings I'm trying are very simple - just block youtube.com all days.
I don't mind sharing my settings here:
[LeechBlockOptions.txt](https://github.com/proginosko/LeechBlockNG-chrome/files/6629036/LeechBlockOptions.txt)

**Comment by proginosko** [comment]
Thanks for posting it here.

You need to specify either a time period or a time limit for the sites to be blocked. If you want to completely block YT, enter `0000-2400` for the time period.

Let us know if it works once you've done that.

**Comment by tuket** [comment]
Thanks for your reply.
No, it doesn't work either.

**Comment by proginosko** [comment]
I don't use Vivaldi, so I won't be much help here. But if it has an error console, open it and see if any error messages appear when you access a site that ought to be blocked.

**Comment by tuket** [comment]
![Screenshot from 2021-06-11 16-40-19](https://user-images.githubusercontent.com/4165974/121704186-cd86b600-cad3-11eb-86b5-cf3eb3e1a554.png)

**Comment by proginosko** [comment]
Thanks. Please clear the console, then visit youtube.com in a fresh tab, then post a screenshot of the console. I don't see any errors related to LB in the screenshot you posted, but I want to be sure.

**Comment by tuket** [comment]
Hi, I don't know what I was doing wrong but I got LeechBlock working now.
I think it might have been due to having other extensions active. I have uninstalled a few, so I'm not sure exactly which one might have been.
Thanks for your help!

**Comment by proginosko** [comment]
Okay, good! Feel free to reopen this issue if you have problems again.
