### ISSUE TITLE
LHs

### ISSUE THREAD

**Issue by SrikarBharadwajR** [proginosko/LeechBlockNG-chrome#37]
Hey as you told, I removed my review from chrome web store and updated it here 
1. By changing time zone in windows settings (So that i could set my time zone where that time is equal to the time for which I have set to unblock)
2. Pressing Shift + Escape and opening task manger and ending the process of LeechBlock (I just overcome it by using another extension which allows me to control key board shortcut and I modified it and it successfully worked)
3. Clicking on Extension icon on the top right corner of the browser and Removing it from chrome(this could be fixed by just removing that extension icon(jig saw one) which was possible before the chrome 91 update in experiments section).
I request the creator (James Anderson) of this extension  to look into these loop holes which I have found.
But anyway thank you very much for creating this extension.

**Comment by proginosko** [comment]
Thanks for removing the review and posting your comments here.

I don't have a workaround for 1 at this time.

For 2: You can set the Chrome Enterprise policy [TaskManagerEndProcessEnabled](https://chromeenterprise.google/policies/#TaskManagerEndProcessEnabled) to false to prevent the user from ending the process.

For 3: See [FAQ entry](https://www.proginosko.com/leechblock/faq/remove-extension-chrome/).
