### ISSUE TITLE
Animations on page are being stuttered every second

### ISSUE THREAD

**Issue by loneshaman** [proginosko/LeechBlockNG-chrome#4]
I've been noticing some scroll, video and typing stuttering for a while now. It makes scrolling any page or typing anything a chore, and makes any videos nigh unwatchable. Going into the dev tools showed me that at least the scrolling issue seems to be linked to the counter, since the scroll stuttered every time the timer counted down. Haven't tested it thoroughly, so that's just a preliminary verdict. Disabling the extension removes the scrolling, typing and video issues.

**Comment by proginosko** [comment]
Thanks for the report. Does the issue still occur when the timer is hidden? (See under General options.)

Which OS are you using? Can you give a specific example of a site (esp. video) that causes the problem?

**Comment by loneshaman** [comment]
I'm using macOS v10.12.6. Youtube is especially jarring, with video stuttering every other second. And any and every site has scroll stuttering. Removing the timer overlay does not stop the issue, and for good measure, neither does removing the timer on the icon.

For comparison, I also use Leechblock NG for Firefox (what can I say? I'm a fan) and I have had no such issues.

**Comment by proginosko** [comment]
Thanks, that's very helpful. I will investigate!

**Comment by loneshaman** [comment]
No problem. Let me know if I can help more.

On Feb 9, 2018 11:06 AM, "James Anderson" <notifications@github.com> wrote:

Thanks, that's very helpful. I will investigate!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/proginosko/LeechBlockNG-chrome/issues/4#issuecomment-364528800>,
or mute the thread

**Comment by proginosko** [comment]
I haven't been able to reproduce the problem (although I'm using Win10 not macOS). Could you please export your settings and email them to me (leechblockng@proginosko.com)? If you can find a minimal setup that generates the problem, that would be ideal.
