### ISSUE TITLE
Urls with https in the middle don't work

### ISSUE THREAD

**Issue by Lazerbeak12345** [proginosko/LeechBlockNG-chrome#40]
A URL such as `web.archive.org/web/20210416195310/https://example.com` will not work in leechblock as it gets replaced with `web.archive.org/web/20210416195310/example.com` (changing the meaning of the URL)

**Comment by proginosko** [comment]
Good catch! That'll be fixed in the next release.

**Comment by proginosko** [comment]
Fixed in version 1.3.1.
