### ISSUE TITLE
Lockdown hours/minutes boxes are small, and their respective dropdowns do not work

### ISSUE THREAD

**Issue by nik312123** [proginosko/LeechBlockNG-chrome#42]
Here is what the lockdown page looks like with 2 entered in both the hour(s) and minute(s) input boxes:

![lockdown](https://user-images.githubusercontent.com/24688726/155859181-b680af68-118c-4d4c-8bae-584d0572dee2.png)

The drop-down chevrons also do nothing upon being clicked.

**Comment by nik312123** [comment]
I am on macOS Mojave 12.2.1. This was also the case on my older Mac, which has been on macOS Mojave 10.14.6 and Catalina 10.15.7.

**Comment by proginosko** [comment]
Thanks. Try this for me, if you don't mind:
- Open the Lockdown page
- Open the browser console (Cmd+Shift+J)
- Enter this line of code followed by ENTER: `document.getElementById("hours").size=6;`

Does the hour(s) field look/work any better after that?

**Comment by nik312123** [comment]
Yes, it does. The effect goes away upon clicking on the input box, though, which is probably how the application is coded.

Also, I was incorrect about the dropdowns not working. The dropdowns do work if their respective fields are blank, which is my bad.

![change_size](https://user-images.githubusercontent.com/24688726/155896397-ed1f8586-de00-43b0-ac1f-03c882169e26.gif)

**Comment by proginosko** [comment]
So the upshot is: those two fields need to be wider for your system. Correct?

**Comment by nik312123** [comment]
Yep. That seems to be the case.

**Comment by proginosko** [comment]
Well, that's easily fixed then. I'll expand them in the next release. In the meantime, try some different values than 6 and let me know what's optimal for your setup.

**Comment by nik312123** [comment]
Assuming a 3-digit buffer, 6 seems to work the best. 5 slightly obscures one of the 3 digits but is also fine.

**Comment by proginosko** [comment]
Thanks, that's very helpful. How often would a user want to enter a 3-digit value for either hours or minutes, I wonder?

**Comment by nik312123** [comment]
I have actually done so on several occasions where I want to remove distractions for around a week and do some crunch time.

**Comment by proginosko** [comment]
Ha! That's good to know.

**Comment by proginosko** [comment]
Fixed in version 1.4.
