### ISSUE TITLE
Doesn't block sites on private windows on brave

### ISSUE THREAD

**Issue by amazinglySK** [proginosko/LeechBlockNG-chrome#43]
### Steps to reproduce the issues:
- Add a website to the block list
- Open up a new private window on brave
- Type in that website

### Result 
The website is not blocked by the extension

### Workaround
Opening the debug console in developer mode and keeping it running by the side 

### More details
- OS  : Windows 11
- Browser : Brave (v1.38.117)
- LeechBlock Version : 1.4.2.1

**Comment by proginosko** [comment]
Have you enabled the extension in private browsing mode?

https://brave.com/learn/enable-extensions-in-incognito/

**Comment by amazinglySK** [comment]
Had it on the last day but didn't work. I just ran a random check once again and apparently it works. Don't know the exact issue now. Sorry for the trouble !
