### ISSUE TITLE
Stated time that override will end is wrong

### ISSUE THREAD

**Issue by ElhemEnohpi** [proginosko/LeechBlockNG-chrome#44]
I started using LeechBlock recently and noticed a minor issue: when I do an override, I see a page with a message, e.g. "Override activated. Blocking will be suspended until 9:09:54 a.m.." but the stated time is six hours later than it should be. It should (and does in fact) end at 3:09:54 a.m.

Firefox 100, macOS 12.4, LeechBlock 1.4.2

**Comment by proginosko** [comment]
Does this happen only with the override time? Do you get the same error when a page is blocked (and the blocking page shows the time when the block will end)?

**Comment by ElhemEnohpi** [comment]
I have a setting for 45 minutes in every day. I was using a filter, but if I change to the blocking page, I see `The page will be unblocked at: 2022-05-22, 12:00:00 a.m.`. Seems like it's off by 24 hours, since it's only the 20th today. If it thinks it's six hours later than it actually is, it would now be after midnight and be the 21st already, so that could explain it.

**Comment by proginosko** [comment]
No problem! Glad you figured it out.
