### ISSUE TITLE
Having trouble with preventing leechblock from being uninstalled on brave, Linux.

### ISSUE THREAD

**Issue by AnonymousWatch3r** [proginosko/LeechBlockNG-chrome#45]
Hey, as the title says, I'm having trouble with this. I've read the information linked on this page for linux but I'm still lost. Leechblock is one of my favourite extensions, just a bummer I can easily uninstall it on brave. If anyone knows how to prevent it from being uninstalled on linux,brave. Please let me know.

**Comment by AnonymousWatch3r** [comment]
btw the link I was referring to was this: https://support.google.com/chrome/a/answer/7517525

**Comment by proginosko** [comment]
I don't use Brave or Linux, so the following is nothing more than an educated guess pieced together from information I've gleaned in various places. It seems that you need to put a policies JSON file in the directory `/etc/brave/policies/managed` (and you'll need to create that directory if it doesn't already exist).

So try this:
- Close all Brave windows.
- Download [this policies file](https://github.com/proginosko/LeechBlockNG-chrome/files/8840819/managed_policies.txt), put it in the directory above, and rename it to `managed_policies.json`.
- Restart Brave and see if the LeechBlock extension is locked.

**Comment by AnonymousWatch3r** [comment]
Hey there, sorry for the very late reply. Got caught up with exams. So I have done what you said and now I am this stage:
![Screenshot from 2022-07-13 15-51-48](https://user-images.githubusercontent.com/106559718/178764211-feddb806-3c0e-4bdb-a8f1-e724c5ebb765.png)

It says there is an error but seems like I'm getting close now. It does say the "managed by your organisation" thing but the extension can still be removed or disabled as normal.

**Comment by proginosko** [comment]
Try [this policies file](https://github.com/proginosko/LeechBlockNG-chrome/files/9126446/managed_policies.txt) instead (remember to rename as `.json`).

**Comment by AnonymousWatch3r** [comment]
Thanks a lot @proginosko, you've been great. Thanks for your time and the amazing extension you've made.

**Comment by proginosko** [comment]
So the second version of the policies file worked?
