### ISSUE TITLE
Override does not work

### ISSUE THREAD

**Issue by PythonCoderAS** [proginosko/LeechBlockNG-chrome#47]
I set an override for 120 minutes for a site with 50 seconds remaining for the site. Once the 50 seconds were up, the website got blocked like normal.

**Comment by proginosko** [comment]
Did you select "Allow temporary override for these sites" for the relevant block set?

**Comment by PythonCoderAS** [comment]
Oh I didn't know that was required. It's working as expected now.

**Comment by proginosko** [comment]
No worries. It's easily missed. There is a "Note" in the Temporary Override section of the General options, but I probably need to find some other way of alerting users to this per-block setting.
