### ISSUE TITLE
Please allow delaying the LeechBlock options, LeechBlock override, and chrome://extensions pages

### ISSUE THREAD

**Issue by nik312123** [proginosko/LeechBlockNG-chrome#49]
In an email conversation we had, you had mentioned that you would do the following on April 3, 2022:

> Okay, you persuaded me. :)
> 
> In the next version, it will be possible to block/delay LB extension pages except for the blocking and delaying pages (since that would lead to an endless loop).
> 
> I'm not sure when the next version will be released, however.

However, you may have forgotten our conversation and did not add the capability to delay LeechBlock options, LeechBlock override, and chrome://extensions. It's no problem as you probably have been busy since then, but I figured I would make a GitHub issue to make it easier to track and remember. ;)

Here was my rationale as you had asked for it at the time.

You:
> Some other users have requested the ability to block extensions, so I'll probably restore that in a future version. But I'm inclined to disallow blocking the LeechBlock extension itself. Can you think of a good reason why that would be needed?

Me:
> Certainly. I can explain my particular uses for blocking the LeechBlock extension.
> 
> There are a few pages of LeechBlock I particularly do not want to have easily accessible, and as such, I put a 30-minute delay on them. Those pages in question are the options page and the override page.
> 
> The reason I add a delay for these pages is that I don’t want to easily be able to modify the rules or suspend blocking. Easy access to these pages allows for me to be impulsive and remove rules as desired or override a current block so I can continue procrastinating.

**Comment by proginosko** [comment]
You can do this right now, but you need to use a regular expression to block/delay the LB pages. Enter the following into the field _Use regular expression to match URLs to block_ under Advanced Options:

`^chrome-extension:\/+blaaajhemilngeeffpbfkdjjoefldkok\/(options|override)\.html`

To block/delay **chrome://extensions**, select the option _Prevent access to Extensions page at times when these sites are blocked_ under Advanced Options.

**Comment by nik312123** [comment]
Ah, thanks!
