### ISSUE TITLE
chrome extensions access option, not turned off

### ISSUE THREAD

**Issue by timbo33334** [proginosko/LeechBlockNG-chrome#5]
when block set is active, chrome extensions access is still allowed to be turned off, unlike about:addons in firefox. 
vivaldi :  https://i.imgur.com/h3j5Igj.jpg
firefox:   https://i.imgur.com/BcdFNBc.jpg

**Comment by proginosko** [comment]
Thanks! Good catch. This will be fixed in the next release.
