### ISSUE TITLE
Prefixes Not Working as Anticipated

### ISSUE THREAD

**Issue by ChrisLTheNerd** [proginosko/LeechBlockNG-chrome#50]
When I add a specific sub-site as an exception like +https://www.youtube.com/@minecraft, the main site added to the block list like https://www.youtube.com will override it. Same happens on amazon when adding my order history as an exception. I'm using Chrome Version 108.0.5359.99 (64-bit)

![Screenshot 2022-12-10 165204](https://user-images.githubusercontent.com/50182206/206876788-3106a979-f4f9-44bb-a42c-249cf7a0b86c.png)
![Screenshot 2022-12-10 180406](https://user-images.githubusercontent.com/50182206/206878627-3284f95c-3f5f-42ea-b52b-ee3d56147671.png)
![Screenshot 2022-12-10 164806](https://user-images.githubusercontent.com/50182206/206876786-d0953c0a-5506-45a9-b133-1a2b9983da73.png)

It also happens with keyword prefixes.

![Screenshot 2022-12-10 173208](https://user-images.githubusercontent.com/50182206/206877921-119b05e2-b1d2-41c1-b847-f7acc36fef93.png)
![Screenshot 2022-12-10 173311](https://user-images.githubusercontent.com/50182206/206877922-d7e91415-51d5-4a34-8a80-02b7a52659d7.png)
![Screenshot 2022-12-10 173456](https://user-images.githubusercontent.com/50182206/206877930-8c78ea9f-2796-4910-ac47-57b8c4990546.png)

And here's the issue with Amazon too.

![Screenshot 2022-12-10 180118](https://user-images.githubusercontent.com/50182206/206878586-336a4037-8651-4b86-954c-e935c618b996.png)
![Screenshot 2022-12-10 180153](https://user-images.githubusercontent.com/50182206/206878589-f425e754-52f8-4764-9eac-71533e0ecda5.png)
![Screenshot 2022-12-10 180212](https://user-images.githubusercontent.com/50182206/206878591-e7b45927-20dd-49d6-bd01-f2f4952e2862.png)

**Comment by proginosko** [comment]
You shouldn't include the protocol (https) in the site list. You can also omit the www, since LeechBlock will match sites with or without it. So, for example, your first list should be:

`+youtube.com/@minecraft`
`youtube.com`

**Comment by ChrisLTheNerd** [comment]
Oh, thanks! Sorry to bother you. Also just to be aware, is there a way to make an exception for videos from specific YouTube Channels? I'm aware the channel name is not anywhere on a video link, but I just want to be sure.

**Comment by proginosko** [comment]
Yes, the channel name doesn't appear in the URL, but some users have blocked videos in specific channels by using keyword blocking.
