### ISSUE TITLE
When importing settings without password, don't change the current one

### ISSUE THREAD

**Issue by Anton-V-K** [proginosko/LeechBlockNG-chrome#56]
I usually export settings without passwords (until #55 is fixed).
When I import such settings (in the same or another browser) the currently existing password is reset to blank, which is confusing, since it is easily overlooked (breaking the security) and requires extra step to manually set same password again.
I propose to change this behavior: when there is no password in settings file and current password isn't blank, the import shouldn't touch the corresponding password.
PS: I use only Access Control password, and probably same behavior makes sense for other types of passwords/codes.

**Comment by proginosko** [comment]
Good catch! I'll fix this in the next release.

**Comment by proginosko** [comment]
Fixed in version 1.5.8 (uploaded and under review).
