### ISSUE TITLE
Recently not working on chrome (with windows7)

### ISSUE THREAD

**Issue by cmmsr** [proginosko/LeechBlockNG-chrome#58]
Hi, 
I use windows 7 and this means I cannot receive chrome updates recently. 
And it's been a few days (or weeks in case I didnt notice quickly) that leech block is just not working, which makes me very sad caust it's such an helpful app. It is not blocking pages like it used to.
It it because you made a recent update?
This happen simultneously accross chrome profiles so I dont think it's because I tweeked the options
Thank you! 
Clara

**Comment by proginosko** [comment]
Which version of Chrome are you using?

You can find out from: chrome://settings/help

**Comment by cmmsr** [comment]
Thank you very much for your reply!, the version seems to be :

Version 109.0.5414.120 (Official Build) (64-bit)


Le sam. 2 déc. 2023 à 11:20, James Anderson ***@***.***> a
écrit :

**Comment by Anton-V-K** [comment]
AFAIK updating Chrome to 119.0.6045.200 isn't possible for Windows 7/8.1 users - 109.x.x.x was the last version to support old systems.
@cmmsr , you can try installing an alternative Chromium-forked browser like [Supermium](https://github.com/win32ss/supermium), or downgrading the extension's version as explained in https://github.com/proginosko/LeechBlockNG-chrome/issues/59#issuecomment-1839872799

**Comment by proginosko** [comment]
Closing this because it's not really an issue with LeechBlock. Workaround provided in #59.
