### ISSUE TITLE
Keyword blocks have suddenly stopped working

### ISSUE THREAD

**Issue by rafal423** [proginosko/LeechBlockNG-chrome#6]
Hello, 
When I launched Google Chrome today, I've noticed that none of my keyword blocks work anymore. When I try to create new ones they don't work either. It used to be that when I opened a website containing a blocked word it would jump to the blank page immediately. Now, none of my blocks do that. It's the same on my laptop as well. Can I please have some help?

**Comment by proginosko** [comment]
Apologies! I added some code to the Firefox version to improve performance, but I didn't realize it would break the keyword blocking in the Chrome version. (I guess I tested everything in the Chrome version _except_ keyword blocking...) Anyway, I've implemented a fix in v0.9.3.1. Let me know whether it works for you.

**Comment by rafal423** [comment]
Yeah, everything is working perfectly now. Thanks a lot!
