### ISSUE TITLE
Can't redirect to a custom local html file ?

### ISSUE THREAD

**Issue by vmonteco** [proginosko/LeechBlockNG-chrome#65]
I tried entering a `file:///C:/Users/username/Documents/Back_to_work.html`-like URL under the "_Enter the fully specified URL of the page to show instead of these blocked sites:_" field but it only seems to break the blocking part of the extension (can access pages I shouldn't have access to).

I ensured that the said URL was accessible by entering it in my browser.

Is there something different I could try?

**Comment by proginosko** [comment]
Go to the Extensions page in Chrome, then to the Details page for LeechBlock, and activate "Allow access to file URLs."

**Comment by vmonteco** [comment]
Thank you @proginosko. Worked like a charm!
