### ISSUE TITLE
Keyword blocks have stopped working again

### ISSUE THREAD

**Issue by rafal423** [proginosko/LeechBlockNG-chrome#7]
Hello,
After reinstalling the app my keyword blocks don't work anymore. I've already reported the same issue back in June. Could you please look into this? Any help would be appreciated.

**Comment by proginosko** [comment]
It's working for me on Chrome for Windows. Please export your settings to a text file (Options > General > Export) and email them to leechblockng@proginosko.com with an example of a site that isn't blocked but should be.
