### ISSUE TITLE
Leechblock not working since today. 

### ISSUE THREAD

**Issue by AlphaeusNg** [proginosko/LeechBlockNG-chrome#71]
It has been working fine for me for years. Didn't change anything, noticed that the countdown didn't appear on the top left side.

Example:
![image](https://github.com/proginosko/LeechBlockNG/assets/78588510/cc5e72af-fc64-49a1-a9ad-49d7d49a37dc)

But it's not blocking:
![image](https://github.com/proginosko/LeechBlockNG/assets/78588510/6300a834-9bd8-4f2e-802c-3ace5e0be40c)

**Comment by proginosko** [comment]
Please export your options to a text file (Options > General > Export Options) and email it to me at leechblockng@proginosko.com so I can take a closer look.

**Comment by AlphaeusNg** [comment]
![image](https://github.com/proginosko/LeechBlockNG-chrome/assets/78588510/8c4d1ec4-206f-48a9-ba63-8e91dd24e6bc)

Hi my option is locked... how should I open it?

But today, leechblock seems to be working fine again.

**Comment by proginosko** [comment]
Email me for instructions.

**Comment by proginosko** [comment]
I didn't receive any email address, except the GitHub one that sends the reply to this thread.

Please email me **directly** at leechblockng@proginosko.com.
