### ISSUE TITLE
Override duration to apply like normal limits instead of counting down automatically

### ISSUE THREAD

**Issue by KL13NT** [proginosko/LeechBlockNG-chrome#74]
I want to use the override feature to give myself more time temporarily on a certain block. What I expect is:
1. Override is set to 5 minutes
2. I visit the website for 1 minute
3. Close the tab
4. Come back 5 hours later and find 4 minutes remaining in my override

Is this possible somehow? Would appreciate pointing me in the right direction to fork and edit it myself if not possible :)

**Comment by proginosko** [comment]
This is currently not possible. I recommend posting it as a feature request in the [main (Firefox) repository](https://github.com/proginosko/LeechBlockNG/discussions/categories/ideas).

**Comment by KL13NT** [comment]
Created one here. https://github.com/proginosko/LeechBlockNG/discussions/466
