### ISSUE TITLE
multiple time periods for blocking  not functional

### ISSUE THREAD

**Issue by WaterSibilantFalling** [proginosko/LeechBlockNG-chrome#77]
![2024-08-30_08-56](https://github.com/user-attachments/assets/7dff856d-f500-42af-87fa-56f4fdf220ac)

As per the image, Leechblock cannot handle more than one time period when the time periods are specified according to leechblock's rules.

**Comment by proginosko** [comment]
"8300" is not a valid time. I assume you meant "0830".

**Comment by WaterSibilantFalling** [comment]
oh for f..k's sake. closing ...
