### ISSUE TITLE
Google profiles

### ISSUE THREAD

**Issue by ArkadiKirsanov** [proginosko/LeechBlockNG-chrome#79]
Chrome allows you to create a number of profiles or use a guest profile. Extensions installed in on profile, don't transfer to the others. This means blocks are easily avoided by using another profile. Does anybody have a solution to this?

**Comment by ArkadiKirsanov** [comment]
Thanks for the quick reply! I've tried it, but my registry looks different. Under the policy file there is no seperate google file beneath which I can add a key.

**Comment by proginosko** [comment]
You can just add a new key **Google** under **Policies**, and then add the **Chrome** key under **Google**.

However, it occurs to me is that what you really want to do is prevent users from creating new profiles or using the guest profile. You can also do that with Chrome Enterprise policies: see [BrowserAddPersonEnabled](BrowserAddPersonEnabled) and [BrowserGuestModeEnabled](https://chromeenterprise.google/policies/#BrowserGuestModeEnabled). Set them both to DWORD value 0 (false).

**Comment by ArkadiKirsanov** [comment]
Thanks! That is what I want indeed. Can I keep all default values/info when making those keys? I would need to pay for google enterprise/workspace in the latter case correct?

Verstuurd vanaf mijn iPhone

Op 18 okt. 2024 om 18:02 heeft James Anderson ***@***.***> het volgende geschreven:

﻿

You can just add a new key Google under Policies, and then add the Chrome key under Google.

However, it occurs to me is that what you really want to do is prevent users from creating new profiles or using the guest profile. You can also do that with Chrome Enterprise policies: see BrowserAddPersonEnabled and BrowserGuestModeEnabled<https://chromeenterprise.google/policies/#BrowserGuestModeEnabled>. Set them both to DWORD value 0 (false).

**Comment by proginosko** [comment]
> Thanks! That is what I want indeed. Can I keep all default values/info when making those keys? I would need to pay for google enterprise/workspace in the latter case correct?

Not sure what you mean. You shouldn't have to pay anything at all. Just put those two entries into your registry and you should be good to go. I just tested it on my system (Chrome on Windows 11).

**Comment by proginosko** [comment]
Here's a registry export/import file that will add those two entries automatically. You'll need to change the file extension from **txt** to **reg** to use it.

[ChromeDisableAddUserAndGuest.txt](https://github.com/user-attachments/files/17439094/ChromeDisableAddUserAndGuest.txt)

**Comment by ArkadiKirsanov** [comment]
Thanks so much! I managed to do it using you file. For others: if you're as much a noob as me on this registry business: Save the file to a registry file by adding .reg to the title of the document when saving it. Then go to the registry and click file>import, than search for your recent download.
