### ISSUE TITLE
Leechblock / No longer working.

### ISSUE THREAD

**Issue by Bacchinif** [proginosko/LeechBlockNG-chrome#81]
Hey everyone, 

I recently installed this Chrome Extension, however it completely stopped working after 2 days. I have tried re-installing it, but nothing changed. The extension should be having all the permissions. What should I do?

**Comment by proginosko** [comment]
Go to the Extensions page (**chrome://extensions**). Click on "Details" under LeechBlock NG. Under "Site access" ensure that "On all sites" is selected. If it was already selected, report back here and we'll investigate further.

**Comment by Bacchinif** [comment]
> Go to the Extensions page (**chrome://extensions**). Click on "Details" under LeechBlock NG. Under "Site access" ensure that "On all sites" is selected. If it was already selected, report back here and we'll investigate further.

Thank you very much for your prompt reply. I had already checked that and unfortunately it hasn't solved the issue. 

I may have already found a workaround. You should select "Process only active tabs (improves performance when multiple tabs open)" from the options panel. I had this unticked previously and the extension wasn't subtracting spent time on websites from the total count.

**Comment by proginosko** [comment]
You should only need that option if you have a large number of tabs open (or a very long list of sites to block). Is that the case?

**Comment by Bacchinif** [comment]
> You should only need that option if you have a large number of tabs open (or a very long list of sites to block). Is that the case?

No, I only had 2 tabs open - however, ticking that option seems to have solved my issue for now.
